# Generated by Django 4.0 on 2021-12-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('mercancias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalIndicador',
            new_name='HistoricalIndicadores',
        ),
        migrations.RenameModel(
            old_name='HistoricalMeasureUnit',
            new_name='HistoricalMeasureUnite',
        ),
        migrations.RenameModel(
            old_name='Indicador',
            new_name='Indicadores',
        ),
        migrations.RenameModel(
            old_name='MeasureUnit',
            new_name='MeasureUnite',
        ),
    ]
